on:
  workflow_dispatch:
  push:
    branches:
        - master
  pull_request:
    branches:
      - master
    types:
      - opened
      - synchronize
jobs:
  scan_job:
    name: Boost Security Scanner
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to ECR
        uses: docker/login-action@v1
        with:
          registry: 706352083976.dkr.ecr.us-east-2.amazonaws.com
      - name: BoostSecurity Scanner
        uses: peaudecastor/boost-security-scanner-github@master-v2
        with:
          action: scan
          api_token: ${{ secrets.BOOST_API_TOKEN }}
